# Configuración de despliegue para conmutador
APP_STACK="python"
PROJECT_ROOT="/home/mbriseno/code/conmutador"
PROJECT_BRANCH="main"
VENV_PATH="$PROJECT_ROOT/venv"
PM2_NAME="conmutador"
PM2_START_CMD='pm2 start $VENV_PATH/bin/python --name $PM2_NAME --cwd $PROJECT_ROOT -- -m uvicorn main:app --host 0.0.0.0 --port 7860'
