# Configuración de despliegue para infra-timelapse
APP_STACK="svelte"
PROJECT_ROOT="/home/mbriseno/code/infra-timelapse"
PROJECT_BRANCH="main"
PM2_NAME="infra-timelapse"
PM2_START_CMD='pm2 start npm --name infra-timelapse --cwd /home/mbriseno/code/infra-timelapse -- run preview'
