APP_STACK="python"
PROJECT_ROOT="/home/mbriseno/code/nexus_back"
PROJECT_BRANCH="main"
VENV_PATH="$PROJECT_ROOT/venv"
PM2_NAME="nexus-back-api"
PM2_START_CMD='pm2 start /home/mbriseno/code/nexus_back/venv/bin/python --name nexus-back-api --interpreter none --cwd /home/mbriseno/code/nexus_back -- -m uvicorn app:app --host 0.0.0.0 --port 8083'
