# Configuración de despliegue para notificaciones_twilio
PROJECT_ROOT="/home/mbriseno/code/notificaciones_twilio"
PROJECT_BRANCH="main"
VENV_PATH="$PROJECT_ROOT/venv"
PM2_NAME="notificaciones-twilio"
APP_ENV="prod"
