# Configuración de despliegue para sandbox_mensajes
APP_STACK="svelte"
PROJECT_ROOT="/home/mbriseno/code/sandbox_mensajes"
PROJECT_BRANCH="main"
PM2_NAME="sandbox-mensajes"
PM2_START_CMD='pm2 start npm --name sandbox-mensajes --cwd /home/mbriseno/code/sandbox_mensajes -- run preview'
