# Configuración de despliegue para santander_ia
APP_STACK="python"
PROJECT_ROOT="/home/mbriseno/code/santander_ia"
PROJECT_BRANCH="main"
VENV_PATH="$PROJECT_ROOT/venv"
PM2_NAME="santander_ia"
PM2_START_CMD='pm2 start /home/mbriseno/code/santander_ia/venv/bin/python --name santander_ia --cwd /home/mbriseno/code/santander_ia -- -m gunicorn app:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8100'
