# Configuración de despliegue para webhook-central-ui
APP_STACK="svelte"
PROJECT_ROOT="/home/mbriseno/code/webhook-central-ui"
PROJECT_BRANCH="main"
PM2_NAME="webhook-central-ui"
POST_BUILD="ln -sf /home/mbriseno/webhook-central/apps.json $PROJECT_ROOT/dist/apps.json && ln -sfn /home/mbriseno/webhook-central/logs $PROJECT_ROOT/dist/logs"
